apiVersion: v1
kind: Namespace
metadata:
  name: argocd1
  
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0cmdzdHIuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImViNGZlMjM4LTQ5OTUtNGI3Yy04ZDIzLTc2YmIxZGU5ZmMxZiIsInBhc3N3b3JkIjoiZk10N1F+aW1BNGwyMnktLW9IcmRfWE1pQjVMUnlpeVVqa0FYSSIsImVtYWlsIjoic3Jpbml2YXNhbkBvcHNlcmEuaW8iLCJhdXRoIjoiWldJMFptVXlNemd0TkRrNU5TMDBZamRqTFRoa01qTXROelppWWpGa1pUbG1ZekZtT21aTmREZFJmbWx0UVRSc01qSjVMUzF2U0hKa1gxaE5hVUkxVEZKNWFYbFZhbXRCV0VrPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: argo-demo-secret
type: kubernetes.io/dockerconfigjson
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: argo-demo-secret
      containers:
        - name: back-end
          image: the-my-app
          ports:
            - containerPort: 8072
          env:
          - name: DOCKER_ENV
            value: "dev"

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argo-demo
  name: argo-demo
spec:
  ports:
  - name: http
    port: 8072
    protocol: TCP
    targetPort: http
  selector:
    app: web
  sessionAffinity: None
  type: NodePort

---
