apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: the-my-app
  newName: testrgstr.azurecr.io/test
  newTag: 0da84564777ff6838f8a320fd6ea4f7226bc3b7f
