apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: the-my-app
  newName: 440953937617.dkr.ecr.us-east-2.amazonaws.com/spring-boot-repo
  newTag: 5e9c3abe49161204c812ee18231da2f544dd4958
