apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namespace: argocd
images:
- name: the-my-app
  newName: 440953937617.dkr.ecr.us-east-2.amazonaws.com/github-integrator
  newTag: 20230104-20230104065832-3
